### PR TITLE
releasing 1.0 

### PR DESCRIPTION
**Pull request by keighrim**

### CODE REVIEW

**Comment by keighrim** [comment]
Good to go? Any idea, anybody?

**Comment by shuchenku** [comment]
I think we are ready to submit, our loader test results are miles ahead of other groups.
I'll update github page according to the latest README.

**Comment by keighrim** [comment]
https://github.com/keighrim/cs105_nT/releases/tag/v1.0
Thank you all for your hard work on the project!

**Comment by shuchenku** [comment]
Thank you Keigh! Awesome work and great management of the project!

**Pull request merged**
